# Generated by Django 5.1.1 on 2024-10-25 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_menuitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='name',
            new_name='dishName',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='preparation_time',
            new_name='preparationTime',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='quantity',
        ),
    ]
